### ISSUE TITLE
Component-List

### ISSUE THREAD

**Issue by JanLoebel** [adlerweb/MoraBoard#2]
Hi there,

I think for many people (specially beginner - like me) it would help to have a (example) component list and a wire-diagram without the pcb.

Example with Reichelt-Links (shop in Germany):

- U1: PCF8563TS -> https://www.reichelt.de/i-c-real-time-clock-tssop-8-pcf8563ts-5-p270122.html

- C2 / C3: 22pF Capacitor -> https://www.reichelt.de/glimmer-kondensator-22pf-100v-5-cy-22-2-22p-p42423.html

- C1 / C4: 100nF Capacitor -> https://www.reichelt.de/vielschicht-keramikkondensator-100n-10-x7r-2-5-100n-p22853.html

- R2 / R3 / R5 / R6: 1.2k Ohm Resistor -> https://www.reichelt.de/widerstand-metalloxyd-1-2-kohm-0207-1-0-w-5-1w-1-2k-p1768.html

- R1 / R4: 120k Ohm Resistor https://www.reichelt.de/widerstand-metalloxyd-120-kohm-0207-1-0-w-5-1w-120k-p1783.html

I'm missing the quartz crystal and the two mosfets, I was not able to find the right one so far. Of course you could also use other resistor/capacitor-types. Any other suggestions? 

Best regards,
Jan

**Comment by adlerweb** [comment]
When using KiCAD both are included. Also there is an interactive BOM located [inside the Hardware folder](https://raw.githubusercontent.com/adlerweb/uPoff/master/hardware/bom/ibom.html) - sadly GitHub doesn't render HTML directly, so you have to save and open it locally.

For your Links: I guess you're designing your own board or using a breadboard/prototype, otherwise you might want to check your footprints.

Crystal is [anything with 32.768kHz](https://www.reichelt.de/mini-uhrenquarz-0-032768-mhz-tc38-0-032768-p1089.html?), FETs are AO3407 (Q2/P) and SI2302 (Q1/N).

Items I used where mostly sourced from LCSC:

| Reference   | Quantity | Footprint | Value     | LCSC #  |
|-------------|----------|-----------|-----------|---------|
| C1,C4       | 2        | 0402      | 100nF     | C1525   |
| C2,C3       | 2        | 0402      | 22pF      | C115618 |
| R2,R3,R5,R6 | 4        | 0402      | 1.2kΩ     | C100581 |
| R1,R4       | 2        | 0402      | 120kΩ     | C384380 |
| U1          | 1        | HTSOP8    | PCF8563TS | C269877 |
| Y1          | 1        | C38       | 32.768kHz | C52082  |
| Q1          | 1        | SOT-23    | SI2302    | C351399 |
| Q2          | 1        | SOT-23    | AO3407    | C351408 |

**Comment by JanLoebel** [comment]
Thanks :) I will have a look and KiCAD is new for me, so I will check how to see the wirediagramm. And yes I will start with a breadboard variant :) Thanks for the information!
